In [2]:
# Import Dependencies
import pandas as pd
import json
import re

In [3]:
# Path to the Zillow Home Sales .CSV file
zillow = "data/zillow_sales_data.csv"

# Read our Zillow Home Sales data into pandas
zillow_df = pd.read_csv(zillow)
zillow_df.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,...,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30
0,102001,0,United States,Country,NaN,195075.0,196575.0,198742.0,200333.0,201133.0,...,259167.0,256833.0,255833.0,257333.0,256500.0,257000.0,258667.0,262833.0,264167.0,266500.0
1,394913,1,"New York, NY",Msa,NY,NaN,NaN,NaN,NaN,NaN,...,428897.0,423230.0,418000.0,413667.0,415333.0,417333.0,420000.0,422500.0,424500.0,434500.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,503333.0,496333.0,491083.0,482750.0,469917.0,...,661333.0,653000.0,651667.0,651667.0,653667.0,657000.0,665333.0,668333.0,665667.0,667333.0
3,394463,3,"Chicago, IL",Msa,IL,248333.0,248333.0,251667.0,254333.0,256250.0,...,241000.0,235833.0,232167.0,231500.0,228167.0,226500.0,231500.0,244167.0,251667.0,255000.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,149667.0,153000.0,155667.0,158333.0,159329.0,...,274548.0,271648.0,269667.0,271333.0,269667.0,270333.0,271833.0,278500.0,281000.0,285500.0
5,394974,5,"Philadelphia, PA",Msa,PA,220996.0,225330.0,230000.0,237667.0,242667.0,...,262500.0,254483.0,248633.0,248633.0,245333.0,240667.0,240667.0,252000.0,261667.0,267103.0
6,394692,6,"Houston, TX",Msa,TX,152641.0,154467.0,157300.0,160667.0,161986.0,...,244937.0,241843.0,241500.0,244833.0,243333.0,243663.0,242738.0,248405.0,248741.0,253000.0
7,395209,7,"Washington, DC",Msa,DC,364582.0,368459.0,375126.0,381826.0,378953.0,...,415164.0,406831.0,405167.0,410000.0,406333.0,406333.0,411758.0,428424.0,434161.0,433736.0
8,394856,8,"Miami-Fort Lauderdale, FL",Msa,FL,267217.0,265667.0,265333.0,265667.0,265667.0,...,289333.0,289500.0,291167.0,293833.0,293000.0,293000.0,295000.0,302333.0,307333.0,314000.0
9,394347,9,"Atlanta, GA",Msa,GA,185617.0,188167.0,191167.0,193667.0,193000.0,...,255833.0,252500.0,252500.0,253650.0,252317.0,254150.0,257833.0,267500.0,268838.0,269505.0

In [4]:
# Remove any RegionType that is not a US Metro
zillow_df = zillow_df.loc[(zillow_df["RegionType"] == "Msa")]

zillow_df

,RegionID,SizeRank,RegionName,RegionType,StateName,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,...,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30
1,394913,1,"New York, NY",Msa,NY,NaN,NaN,NaN,NaN,NaN,...,428897.0,423230.0,418000.0,413667.0,415333.0,417333.0,420000.0,422500.0,424500.0,434500.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,503333.0,496333.0,491083.0,482750.0,469917.0,...,661333.0,653000.0,651667.0,651667.0,653667.0,657000.0,665333.0,668333.0,665667.0,667333.0
3,394463,3,"Chicago, IL",Msa,IL,248333.0,248333.0,251667.0,254333.0,256250.0,...,241000.0,235833.0,232167.0,231500.0,228167.0,226500.0,231500.0,244167.0,251667.0,255000.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,149667.0,153000.0,155667.0,158333.0,159329.0,...,274548.0,271648.0,269667.0,271333.0,269667.0,270333.0,271833.0,278500.0,281000.0,285500.0
5,394974,5,"Philadelphia, PA",Msa,PA,220996.0,225330.0,230000.0,237667.0,242667.0,...,262500.0,254483.0,248633.0,248633.0,245333.0,240667.0,240667.0,252000.0,261667.0,267103.0
6,394692,6,"Houston, TX",Msa,TX,152641.0,154467.0,157300.0,160667.0,161986.0,...,244937.0,241843.0,241500.0,244833.0,243333.0,243663.0,242738.0,248405.0,248741.0,253000.0
7,395209,7,"Washington, DC",Msa,DC,364582.0,368459.0,375126.0,381826.0,378953.0,...,415164.0,406831.0,405167.0,410000.0,406333.0,406333.0,411758.0,428424.0,434161.0,433736.0
8,394856,8,"Miami-Fort Lauderdale, FL",Msa,FL,267217.0,265667.0,265333.0,265667.0,265667.0,...,289333.0,289500.0,291167.0,293833.0,293000.0,293000.0,295000.0,302333.0,307333.0,314000.0
9,394347,9,"Atlanta, GA",Msa,GA,185617.0,188167.0,191167.0,193667.0,193000.0,...,255833.0,252500.0,252500.0,253650.0,252317.0,254150.0,257833.0,267500.0,268838.0,269505.0
10,394404,10,"Boston, MA",Msa,MA,329333.0,340333.0,349417.0,355083.0,356717.0,...,468667.0,458667.0,450000.0,451667.0,454167.0,456475.0,465793.0,480160.0,492851.0,501867.0
11,395057,11,"San Francisco, CA",Msa,CA,578667.0,573667.0,563667.0,552667.0,531167.0,...,789333.0,797583.0,800917.0,803750.0,778833.0,767333.0,781833.0,815167.0,837917.0,847917.0
12,394532,12,"Detroit, MI",Msa,MI,134683.0,134750.0,136083.0,137750.0,140333.0,...,200783.0,196783.0,193450.0,189333.0,185967.0,182633.0,183300.0,190000.0,195000.0,200000.0
13,395025,13,"Riverside, CA",Msa,CA,318000.0,309167.0,304167.0,296167.0,284333.0,...,376000.0,375333.0,374333.0,374000.0,374000.0,378333.0,382000.0,383667.0,383833.0,386833.0
14,394976,14,"Phoenix, AZ",Msa,AZ,226133.0,225500.0,225333.0,221667.0,217317.0,...,293333.0,296667.0,297892.0,299558.0,299525.0,301633.0,304467.0,306167.0,304500.0,305000.0
15,395078,15,"Seattle, WA",Msa,WA,348487.0,348393.0,350000.0,349298.0,346042.0,...,481333.0,480000.0,479333.0,487667.0,487998.0,496998.0,505323.0,518991.0,517324.0,520667.0
16,394865,16,"Minneapolis-St Paul, MN",Msa,MN,218333.0,219333.0,219500.0,219500.0,219500.0,...,279775.0,278109.0,276514.0,275738.0,274072.0,273333.0,279334.0,289334.0,296000.0,298000.0
17,395056,17,"San Diego, CA",Msa,CA,458333.0,445000.0,443333.0,431667.0,424667.0,...,584167.0,584833.0,587333.0,588667.0,591333.0,592500.0,599500.0,601167.0,598333.0,600000.0
18,395121,18,"St. Louis, MO",Msa,MO,150300.0,155667.0,159333.0,163333.0,163000.0,...,192000.0,190667.0,187667.0,188215.0,185881.0,181881.0,182583.0,188917.0,196667.0,203750.0
19,395148,19,"Tampa, FL",Msa,FL,176663.0,178230.0,178230.0,179400.0,177833.0,...,234067.0,232400.0,230833.0,232133.0,231600.0,232229.0,232296.0,237796.0,241497.0,245963.0
20,394358,20,"Baltimore, MD",Msa,MD,257917.0,258633.0,263896.0,268896.0,272263.0,...,307565.0,300996.0,298321.0,297992.0,290658.0,285000.0,284000.0,294333.0,302250.0,305983.0
21,394530,21,"Denver, CO",Msa,CO,241922.0,241255.0,241458.0,244750.0,246017.0,...,424800.0,421633.0,421800.0,420167.0,420833.0,422417.0,430750.0,435250.0,437333.0,437681.0
22,394982,22,"Pittsburgh, PA",Msa,PA,121667.0,123667.0,125929.0,130595.0,131262.0,...,182667.0,177667.0,173333.0,171667.0,168300.0,162800.0,164467.0,172833.0,181667.0,186667.0
23,394998,23,"Portland, OR",Msa,OR,271667.0,274332.0,277299.0,280966.0,279967.0,...,402583.0,400917.0,401000.0,402000.0,402000.0,401667.0,406709.0,411709.0,415042.0,419000.0
24,394458,24,"Charlotte, NC",Msa,NC,174967.0,175800.0,177025.0,181528.0,183028.0,...,261000.0,257667.0,256333.0,258333.0,256667.0,258000.0,260667.0,267333.0,268000.0,269333.0
25,395045,25,"Sacramento, CA",Msa,CA,323167.0,314333.0,307167.0,300000.0,294333.0,...,418333.0,415000.0,413333.0,411667.0,410000.0,411667.0,418333.0,426667.0,430000.0,435000.0
26,395055,26,"San Antonio, TX",Msa,TX,149770.0,152237.0,155653.0,156715.0,156748.0,...,233667.0,232983.0,230850.0,231850.0,229200.0,230833.0,230833.0,235333.0,238733.0,242908.0
27,394943,27,"Orlando, FL",Msa,FL,223450.0,220000.0,218333.0,217767.0,217100.0,...,262663.0,260163.0,257663.0,258167.0,259967.0,262800.0,262800.0,266167.0,268000.0,271333.0
28,394466,28,"Cincinnati, OH",Msa,OH,144833.0,146854.0,149687.0,151021.0,153000.0,...,187000.0,183833.0,183483.0,183483.0,180617.0,178933.0,182267.0,190133.0,195150.0,199817.0
29,394475,29,"Cleveland, OH",Msa,OH,133767.0,134733.0,136966.0,137633.0,138966.0,...,158833.0,154667.0,151333.0,148667.0,148667.0,148333.0,153000.0,158667.0,164000.0,167333.0
30,394735,30,"Kansas City, MO",Msa,MO,151967.0,156500.0,159917.0,161750.0,160550.0,...,227000.0,222000.0,218667.0,220000.0,220667.0,220667.0,225500.0,232333.0,239833.0,243300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,394531,91,"Des Moines, IA",Msa,IA,152667.0,152583.0,157250.0,156917.0,158583.0,...,222333.0,219500.0,218500.0,221500.0,220667.0,213500.0,210167.0,215000.0,222833.0,227167.0
92,394711,92,"Jackson, MS",Msa,MS,131829.0,135246.0,137750.0,144251.0,147667.0,...,187467.0,186400.0,185733.0,188900.0,185800.0,186467.0,190550.0,200483.0,205467.0,208383.0
93,394352,94,"Augusta, GA",Msa,GA,127167.0,131133.0,134300.0,139300.0,139517.0,...,185910.0,183310.0,180633.0,184633.0,186333.0,186300.0,188467.0,193433.0,196967.0,200883.0
94,394666,96,"Harrisburg, PA",Msa,PA,158800.0,159133.0,162167.0,163914.0,167214.0,...,193233.0,192567.0,189733.0,190500.0,187167.0,184967.0,183300.0,189967.0,196667.0,201667.0
95,395006,100,"Provo, UT",Msa,UT,217150.0,219817.0,219098.0,217431.0,218515.0,...,329000.0,332333.0,333300.0,333933.0,333933.0,336967.0,339000.0,344000.0,341507.0,348140.0
96,394549,104,"Durham, NC",Msa,NC,194917.0,196667.0,197333.0,195333.0,196333.0,...,278957.0,277290.0,281288.0,286648.0,287314.0,285500.0,293833.0,298193.0,302693.0,298693.0
97,394995,119,"Port St. Lucie, FL",Msa,FL,188333.0,183400.0,184400.0,180400.0,177917.0,...,242967.0,246000.0,249089.0,248151.0,248384.0,246362.0,247267.0,247333.0,246267.0,247667.0
98,395183,124,"Vallejo, CA",Msa,CA,350750.0,335083.0,325083.0,325000.0,323833.0,...,448083.0,446417.0,441667.0,444500.0,437833.0,442833.0,443333.0,456833.0,456833.0,464167.0
99,394746,128,"Killeen, TX",Msa,TX,114500.0,118267.0,124333.0,126133.0,126133.0,...,167233.0,169650.0,169892.0,168058.0,164725.0,165667.0,171656.0,176623.0,180456.0,184883.0
100,395048,132,"Salem, OR",Msa,OR,200500.0,203825.0,205992.0,206242.0,205917.0,...,308315.0,306667.0,306000.0,309000.0,308650.0,311983.0,318150.0,322833.0,325167.0,325967.0
101,394927,149,"Ocala, FL",Msa,FL,146200.0,146000.0,147867.0,146900.0,143600.0,...,165167.0,165500.0,167133.0,170433.0,169933.0,168300.0,166333.0,168000.0,166500.0,167667.0
102,394602,159,"Fort Collins, CO",Msa,CO,228417.0,226750.0,224250.0,221007.0,219987.0,...,390575.0,388736.0,387232.0,388828.0,394000.0,392333.0,392300.0,393667.0,399764.0,404089.0
103,394405,162,"Boulder, CO",Msa,CO,326667.0,324333.0,331083.0,327417.0,318083.0,...,534483.0,527817.0,526650.0,529983.0,533763.0,540783.0,545783.0,548670.0,545000.0,540000.0
104,394471,172,"Clarksville, TN",Msa,TN,121067.0,123750.0,131583.0,133667.0,131750.0,...,196633.0,192633.0,192633.0,190300.0,195967.0,199317.0,201650.0,204650.0,207817.0,212817.0
105,394645,177,"Greeley, CO",Msa,CO,204022.0,204522.0,205455.0,209667.0,208886.0,...,359633.0,359667.0,360500.0,359133.0,361048.0,358548.0,364915.0,370785.0,377785.0,376085.0
106,394813,189,"Macon-Bibb County, GA",Msa,GA,132833.0,131833.0,130483.0,128817.0,127150.0,...,145567.0,144917.0,138333.0,139248.0,138330.0,135663.0,139065.0,143317.0,146650.0,146658.0
107,394346,220,"Athens, GA",Msa,GA,161533.0,156433.0,162067.0,165083.0,166266.0,...,216967.0,214467.0,210600.0,213617.0,216350.0,221033.0,226350.0,234105.0,241122.0,237155.0
108,394623,229,"Gainesville, GA",Msa,GA,179150.0,185517.0,190850.0,181267.0,175817.0,...,243127.0,242460.0,243460.0,250188.0,252785.0,257618.0,262260.0,261663.0,261301.0,262008.0
109,395246,244,"Yuba City, CA",Msa,CA,236333.0,222333.0,219000.0,214333.0,212000.0,...,305000.0,303333.0,307500.0,303833.0,304500.0,297667.0,302500.0,308500.0,311167.0,316667.0
110,395009,251,"Punta Gorda, FL",Msa,FL,156333.0,163000.0,165333.0,173667.0,168083.0,...,214967.0,213333.0,215167.0,214817.0,218150.0,218650.0,221367.0,224667.0,226500.0,228783.0
111,395007,253,"Pueblo, CO",Msa,CO,130833.0,130000.0,130133.0,128467.0,133525.0,...,206067.0,207183.0,205883.0,211267.0,207933.0,198267.0,196133.0,207150.0,219150.0,221483.0
112,395094,331,"Sherman, TX",Msa,TX,94967.0,102050.0,104926.0,103009.0,102676.0,...,194000.0,184167.0,185167.0,181500.0,183667.0,179667.0,178233.0,180233.0,183233.0,188333.0
113,394546,343,"Dunn, NC",Msa,NC,162500.0,162833.0,169417.0,163417.0,159917.0,...,204500.0,201083.0,201250.0,202583.0,201167.0,197333.0,196067.0,201567.0,206733.0,211000.0
114,395166,383,"Truckee, CA",Msa,CA,422833.0,405333.0,401667.0,384667.0,399167.0,...,454500.0,462333.0,464583.0,468333.0,447500.0,433083.0,442500.0,457333.0,461333.0,495833.0
115,395153,399,"The Villages, FL",Msa,FL,203067.0,195767.0,196233.0,196450.0,196100.0,...,270822.0,275750.0,272079.0,271746.0,272246.0,277583.0,277833.0,275567.0,272733.0,266400.0
116,394586,504,"Faribault, MN",Msa,MN,167308.0,180442.0,188675.0,192967.0,194633.0,...,254298.0,244965.0,236665.0,228333.0,233833.0,233500.0,235833.0,240333.0,244667.0,256661.0
117,394309,527,"Albemarle, NC",Msa,NC,114667.0,117667.0,125000.0,126500.0,122333.0,...,178250.0,177833.0,174167.0,178665.0,171332.0,174832.0,159833.0,171167.0,169342.0,189008.0
118,394742,595,"Kerrville, TX",Msa,TX,174279.0,170150.0,174500.0,170067.0,176233.0,...,231133.0,259217.0,257633.0,269917.0,247233.0,259317.0,264400.0,272360.0,280693.0,278326.0
119,395091,641,"Shelbyville, TN",Msa,TN,97150.0,102483.0,108067.0,108667.0,109250.0,...,180533.0,182367.0,179967.0,190133.0,189933.0,185300.0,178967.0,175833.0,190233.0,191533.0
120,395230,672,"Wilmington, OH",Msa,OH,109194.0,122333.0,120667.0,118967.0,121500.0,...,131167.0,137133.0,137967.0,135633.0,136233.0,138983.0,136283.0,135867.0,135617.0,147650.0

In [5]:
# Obtain Column names
zillow_df.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2008-04-30', '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31',
       ...
       '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31',
       '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30'],
      dtype='object', length=152)

In [6]:
# Reflect only 2018 housing data from the Zillow Home Sales dataframe
reduced_zillow_df = zillow_df[["RegionName", "2018-01-31", "2018-02-28", "2018-03-31", 
                               "2018-04-30", "2018-05-31", "2018-06-30", "2018-07-31", 
                               "2018-08-31", "2018-09-30", "2018-10-31", "2018-11-30", 
                               "2018-12-31"]]
reduced_zillow_df

,RegionName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31
1,"New York, NY",398500.0,395500.0,394667.0,395000.0,401666.0,410000.0,420000.0,425333.0,425333.0,417000.0,411000.0,404333.0
2,"Los Angeles-Long Beach-Anaheim, CA",612666.0,615666.0,620667.0,632333.0,639333.0,646667.0,651667.0,651952.0,646952.0,643618.0,641667.0,637667.0
3,"Chicago, IL",218833.0,218500.0,222167.0,230000.0,237333.0,243667.0,245333.0,243300.0,236633.0,229754.0,226121.0,222788.0
4,"Dallas-Fort Worth, TX",251921.0,253588.0,255482.0,261661.0,268327.0,273333.0,276667.0,274000.0,267333.0,261333.0,258663.0,259997.0
5,"Philadelphia, PA",228300.0,225667.0,224000.0,229000.0,235000.0,241667.0,246667.0,251000.0,247833.0,242500.0,237467.0,235633.0
6,"Houston, TX",224089.0,223756.0,224323.0,231330.0,237497.0,241497.0,242500.0,240907.0,236907.0,232636.0,230729.0,234063.0
7,"Washington, DC",387982.0,388000.0,388000.0,398000.0,409333.0,415152.0,417318.0,414652.0,407500.0,399098.0,394431.0,399098.0
8,"Miami-Fort Lauderdale, FL",270000.0,269000.0,270667.0,274000.0,278333.0,283333.0,285582.0,285582.0,280582.0,280000.0,281667.0,283333.0
9,"Atlanta, GA",228300.0,229967.0,231100.0,237216.0,243648.0,247797.0,248681.0,245549.0,244133.0,243433.0,243670.0,242837.0
10,"Boston, MA",422300.0,420646.0,424646.0,436480.0,448133.0,462467.0,469967.0,473333.0,458333.0,444667.0,438000.0,435667.0
11,"San Francisco, CA",746667.0,737333.0,760667.0,807333.0,840000.0,855500.0,852833.0,831167.0,802000.0,796000.0,796000.0,786333.0
12,"Detroit, MI",171500.0,169167.0,168500.0,172500.0,179167.0,185067.0,189567.0,191567.0,187400.0,183700.0,178867.0,177800.0
13,"Riverside, CA",352667.0,357667.0,359333.0,362667.0,362667.0,364667.0,367000.0,365333.0,365000.0,361000.0,361000.0,360667.0
14,"Phoenix, AZ",260196.0,262863.0,265000.0,266667.0,269000.0,272000.0,275440.0,275440.0,275656.0,275883.0,277517.0,278633.0
15,"Seattle, WA",450945.0,457612.0,462705.0,483317.0,491650.0,494650.0,487833.0,478740.0,470313.0,463386.0,460046.0,459952.0
16,"Minneapolis-St Paul, MN",247796.0,248463.0,250979.0,255833.0,261833.0,265000.0,266667.0,265633.0,264633.0,264967.0,265000.0,264333.0
17,"San Diego, CA",553167.0,552500.0,555500.0,568000.0,579667.0,586667.0,590000.0,594667.0,595667.0,590667.0,587667.0,581417.0
18,"St. Louis, MO",173671.0,172038.0,171667.0,178233.0,183233.0,188400.0,189483.0,187817.0,183650.0,180000.0,177633.0,178300.0
19,"Tampa, FL",212433.0,210300.0,211300.0,213667.0,217500.0,221333.0,224667.0,225832.0,224498.0,222832.0,224000.0,225208.0
20,"Baltimore, MD",282167.0,273833.0,270833.0,275333.0,286250.0,295583.0,301404.0,303820.0,302454.0,299133.0,298347.0,296380.0
21,"Denver, CO",390592.0,400000.0,405794.0,415794.0,420794.0,425667.0,424000.0,420667.0,414667.0,411656.0,409989.0,410322.0
22,"Pittsburgh, PA",156400.0,154567.0,156900.0,161167.0,164833.0,171500.0,174833.0,177000.0,172000.0,166500.0,162167.0,161500.0
23,"Portland, OR",376663.0,380833.0,385500.0,388833.0,394333.0,399459.0,398926.0,399259.0,392933.0,391767.0,387998.0,387015.0
24,"Charlotte, NC",237300.0,237300.0,234000.0,240332.0,244332.0,250673.0,251675.0,252675.0,247000.0,245333.0,245333.0,248667.0
25,"Sacramento, CA",388667.0,389667.0,391333.0,400250.0,405250.0,409750.0,411167.0,409333.0,408167.0,404833.0,405667.0,402333.0
26,"San Antonio, TX",217912.0,216245.0,214578.0,216633.0,222967.0,226817.0,230017.0,230350.0,226516.0,223599.0,220933.0,222250.0
27,"Orlando, FL",245126.0,245126.0,245796.0,245849.0,249183.0,251516.0,253333.0,255000.0,255997.0,255997.0,255997.0,256667.0
28,"Cincinnati, OH",168667.0,167000.0,168333.0,172167.0,177167.0,179950.0,181783.0,181783.0,178500.0,175555.0,175522.0,175688.0
29,"Cleveland, OH",139917.0,135800.0,135267.0,138883.0,143167.0,148033.0,150250.0,152000.0,150467.0,147967.0,144800.0,141833.0
30,"Kansas City, MO",200000.0,199983.0,203317.0,208317.0,215000.0,218917.0,220750.0,218167.0,212583.0,209709.0,209142.0,209433.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,"Des Moines, IA",199917.0,199917.0,199333.0,202917.0,206083.0,211167.0,212833.0,212667.0,211000.0,206667.0,206000.0,202000.0
92,"Jackson, MS",167200.0,166533.0,170050.0,173467.0,178667.0,184333.0,190167.0,192333.0,190000.0,187500.0,187167.0,183833.0
93,"Augusta, GA",165962.0,169717.0,165492.0,169675.0,169375.0,178183.0,181667.0,184000.0,181250.0,178750.0,178067.0,178783.0
94,"Harrisburg, PA",175650.0,174067.0,169717.0,171183.0,175017.0,178350.0,181450.0,183500.0,181850.0,181583.0,179950.0,181967.0
95,"Provo, UT",281817.0,289667.0,292167.0,295890.0,297023.0,303690.0,309967.0,309983.0,309250.0,306583.0,305933.0,308333.0
96,"Durham, NC",268500.0,267667.0,269833.0,276333.0,278000.0,279667.0,281333.0,283167.0,279833.0,278167.0,279775.0,288108.0
97,"Port St. Lucie, FL",216600.0,215600.0,218333.0,220000.0,223333.0,223333.0,224022.0,225655.0,227322.0,230573.0,228018.0,227148.0
98,"Vallejo, CA",418750.0,419417.0,425083.0,429333.0,434333.0,432667.0,436667.0,438500.0,435833.0,432333.0,432167.0,429167.0
99,"Killeen, TX",150100.0,149100.0,150150.0,155950.0,158250.0,161600.0,163137.0,164803.0,162787.0,160267.0,159952.0,159602.0
100,"Salem, OR",268333.0,270700.0,273850.0,280483.0,283017.0,284867.0,290633.0,295700.0,296033.0,289933.0,286300.0,286798.0
101,"Ocala, FL",146100.0,147117.0,147317.0,149233.0,149917.0,154750.0,159083.0,161250.0,162883.0,162800.0,163283.0,162283.0
102,"Fort Collins, CO",365992.0,369658.0,375492.0,377000.0,382333.0,382633.0,384567.0,382149.0,383116.0,382349.0,384962.0,383861.0
103,"Boulder, CO",500333.0,521633.0,524967.0,531300.0,548000.0,546333.0,536904.0,524294.0,526628.0,529723.0,535000.0,546936.0
104,"Clarksville, TN",163300.0,163300.0,163333.0,166983.0,169983.0,176950.0,180050.0,179383.0,176917.0,174333.0,173583.0,171583.0
105,"Greeley, CO",331667.0,331667.0,331467.0,335367.0,341700.0,341717.0,343268.0,342602.0,343570.0,344785.0,346918.0,349458.0
106,"Macon-Bibb County, GA",130287.0,119983.0,120817.0,127800.0,135600.0,139595.0,138078.0,138112.0,136300.0,134667.0,132667.0,134667.0
107,"Athens, GA",192800.0,196750.0,186442.0,199975.0,206375.0,213017.0,211967.0,207583.0,202583.0,196250.0,196220.0,195220.0
108,"Gainesville, GA",210350.0,212267.0,212150.0,229917.0,238167.0,234100.0,237400.0,233900.0,237967.0,230000.0,241000.0,239400.0
109,"Yuba City, CA",266000.0,270000.0,274667.0,279667.0,279000.0,286667.0,287500.0,289167.0,282500.0,280250.0,280083.0,286417.0
110,"Punta Gorda, FL",190167.0,191500.0,188750.0,195667.0,199000.0,206000.0,203233.0,203233.0,201533.0,203033.0,210700.0,212400.0
111,"Pueblo, CO",171467.0,171867.0,173567.0,179400.0,180833.0,188333.0,191667.0,192500.0,190000.0,185667.0,182300.0,178967.0
112,"Sherman, TX",163667.0,156067.0,164067.0,167900.0,180167.0,185167.0,190300.0,183047.0,184214.0,179914.0,187500.0,179000.0
113,"Dunn, NC",180300.0,176300.0,173467.0,174833.0,176817.0,178900.0,183817.0,183833.0,178167.0,170917.0,173583.0,179333.0
114,"Truckee, CA",432250.0,421667.0,428667.0,442000.0,448583.0,463250.0,465000.0,469917.0,463917.0,465667.0,458833.0,436500.0
115,"The Villages, FL",255862.0,259529.0,263461.0,259464.0,259964.0,263103.0,268070.0,265570.0,261833.0,263833.0,266333.0,273630.0
116,"Faribault, MN",208000.0,208667.0,206967.0,209300.0,208800.0,214667.0,218967.0,226235.0,228402.0,222586.0,217117.0,217451.0
117,"Albemarle, NC",141000.0,139167.0,143250.0,152250.0,149083.0,149000.0,144000.0,151083.0,152083.0,156750.0,153667.0,156667.0
118,"Kerrville, TX",235311.0,232145.0,232145.0,234167.0,245667.0,258667.0,260750.0,252083.0,235250.0,236667.0,245750.0,258750.0
119,"Shelbyville, TN",161400.0,165353.0,161120.0,161453.0,162267.0,163267.0,164100.0,164833.0,177167.0,177500.0,172833.0,159467.0
120,"Wilmington, OH",120133.0,109167.0,132500.0,130167.0,135133.0,128300.0,131800.0,131883.0,133217.0,129383.0,124167.0,122333.0

In [7]:
# Rename Column Headers and Include 2018 Sales Average 
final_zillow_df = pd.DataFrame(columns=["metro_area", "Median Home Price 1/18", 
                                     "Median Home Price 2/18", "Median Home Price 3/18", 
                                     "Median Home Price 4/18", "Median Home Price 5/18", 
                                     "Median Home Price 6/18", "Median Home Price 7/18", 
                                     "Median Home Price 8/18", "Median Home Price 9/18", 
                                     "Median Home Price 10/18", "Median Home Price 11/18", 
                                     "Median Home Price 12/18",])

final_zillow_df["metro_area"] = reduced_zillow_df["RegionName"].values
final_zillow_df["Median Home Price 1/18"] = reduced_zillow_df["2018-01-31"].values
final_zillow_df["Median Home Price 2/18"] = reduced_zillow_df["2018-02-28"].values
final_zillow_df["Median Home Price 3/18"] = reduced_zillow_df["2018-03-31"].values
final_zillow_df["Median Home Price 4/18"] = reduced_zillow_df["2018-04-30"].values
final_zillow_df["Median Home Price 5/18"] = reduced_zillow_df["2018-05-31"].values
final_zillow_df["Median Home Price 6/18"] = reduced_zillow_df["2018-06-30"].values
final_zillow_df["Median Home Price 7/18"] = reduced_zillow_df["2018-07-31"].values
final_zillow_df["Median Home Price 8/18"] = reduced_zillow_df["2018-08-31"].values
final_zillow_df["Median Home Price 9/18"] = reduced_zillow_df["2018-09-30"].values
final_zillow_df["Median Home Price 10/18"] = reduced_zillow_df["2018-10-31"].values
final_zillow_df["Median Home Price 11/18"] = reduced_zillow_df["2018-11-30"].values
final_zillow_df["Median Home Price 12/18"] = reduced_zillow_df["2018-12-31"].values

final_zillow_df

,metro_area,Median Home Price 1/18,Median Home Price 2/18,Median Home Price 3/18,Median Home Price 4/18,Median Home Price 5/18,Median Home Price 6/18,Median Home Price 7/18,Median Home Price 8/18,Median Home Price 9/18,Median Home Price 10/18,Median Home Price 11/18,Median Home Price 12/18
0,"New York, NY",398500.0,395500.0,394667.0,395000.0,401666.0,410000.0,420000.0,425333.0,425333.0,417000.0,411000.0,404333.0
1,"Los Angeles-Long Beach-Anaheim, CA",612666.0,615666.0,620667.0,632333.0,639333.0,646667.0,651667.0,651952.0,646952.0,643618.0,641667.0,637667.0
2,"Chicago, IL",218833.0,218500.0,222167.0,230000.0,237333.0,243667.0,245333.0,243300.0,236633.0,229754.0,226121.0,222788.0
3,"Dallas-Fort Worth, TX",251921.0,253588.0,255482.0,261661.0,268327.0,273333.0,276667.0,274000.0,267333.0,261333.0,258663.0,259997.0
4,"Philadelphia, PA",228300.0,225667.0,224000.0,229000.0,235000.0,241667.0,246667.0,251000.0,247833.0,242500.0,237467.0,235633.0
5,"Houston, TX",224089.0,223756.0,224323.0,231330.0,237497.0,241497.0,242500.0,240907.0,236907.0,232636.0,230729.0,234063.0
6,"Washington, DC",387982.0,388000.0,388000.0,398000.0,409333.0,415152.0,417318.0,414652.0,407500.0,399098.0,394431.0,399098.0
7,"Miami-Fort Lauderdale, FL",270000.0,269000.0,270667.0,274000.0,278333.0,283333.0,285582.0,285582.0,280582.0,280000.0,281667.0,283333.0
8,"Atlanta, GA",228300.0,229967.0,231100.0,237216.0,243648.0,247797.0,248681.0,245549.0,244133.0,243433.0,243670.0,242837.0
9,"Boston, MA",422300.0,420646.0,424646.0,436480.0,448133.0,462467.0,469967.0,473333.0,458333.0,444667.0,438000.0,435667.0
10,"San Francisco, CA",746667.0,737333.0,760667.0,807333.0,840000.0,855500.0,852833.0,831167.0,802000.0,796000.0,796000.0,786333.0
11,"Detroit, MI",171500.0,169167.0,168500.0,172500.0,179167.0,185067.0,189567.0,191567.0,187400.0,183700.0,178867.0,177800.0
12,"Riverside, CA",352667.0,357667.0,359333.0,362667.0,362667.0,364667.0,367000.0,365333.0,365000.0,361000.0,361000.0,360667.0
13,"Phoenix, AZ",260196.0,262863.0,265000.0,266667.0,269000.0,272000.0,275440.0,275440.0,275656.0,275883.0,277517.0,278633.0
14,"Seattle, WA",450945.0,457612.0,462705.0,483317.0,491650.0,494650.0,487833.0,478740.0,470313.0,463386.0,460046.0,459952.0
15,"Minneapolis-St Paul, MN",247796.0,248463.0,250979.0,255833.0,261833.0,265000.0,266667.0,265633.0,264633.0,264967.0,265000.0,264333.0
16,"San Diego, CA",553167.0,552500.0,555500.0,568000.0,579667.0,586667.0,590000.0,594667.0,595667.0,590667.0,587667.0,581417.0
17,"St. Louis, MO",173671.0,172038.0,171667.0,178233.0,183233.0,188400.0,189483.0,187817.0,183650.0,180000.0,177633.0,178300.0
18,"Tampa, FL",212433.0,210300.0,211300.0,213667.0,217500.0,221333.0,224667.0,225832.0,224498.0,222832.0,224000.0,225208.0
19,"Baltimore, MD",282167.0,273833.0,270833.0,275333.0,286250.0,295583.0,301404.0,303820.0,302454.0,299133.0,298347.0,296380.0
20,"Denver, CO",390592.0,400000.0,405794.0,415794.0,420794.0,425667.0,424000.0,420667.0,414667.0,411656.0,409989.0,410322.0
21,"Pittsburgh, PA",156400.0,154567.0,156900.0,161167.0,164833.0,171500.0,174833.0,177000.0,172000.0,166500.0,162167.0,161500.0
22,"Portland, OR",376663.0,380833.0,385500.0,388833.0,394333.0,399459.0,398926.0,399259.0,392933.0,391767.0,387998.0,387015.0
23,"Charlotte, NC",237300.0,237300.0,234000.0,240332.0,244332.0,250673.0,251675.0,252675.0,247000.0,245333.0,245333.0,248667.0
24,"Sacramento, CA",388667.0,389667.0,391333.0,400250.0,405250.0,409750.0,411167.0,409333.0,408167.0,404833.0,405667.0,402333.0
25,"San Antonio, TX",217912.0,216245.0,214578.0,216633.0,222967.0,226817.0,230017.0,230350.0,226516.0,223599.0,220933.0,222250.0
26,"Orlando, FL",245126.0,245126.0,245796.0,245849.0,249183.0,251516.0,253333.0,255000.0,255997.0,255997.0,255997.0,256667.0
27,"Cincinnati, OH",168667.0,167000.0,168333.0,172167.0,177167.0,179950.0,181783.0,181783.0,178500.0,175555.0,175522.0,175688.0
28,"Cleveland, OH",139917.0,135800.0,135267.0,138883.0,143167.0,148033.0,150250.0,152000.0,150467.0,147967.0,144800.0,141833.0
29,"Kansas City, MO",200000.0,199983.0,203317.0,208317.0,215000.0,218917.0,220750.0,218167.0,212583.0,209709.0,209142.0,209433.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,"Des Moines, IA",199917.0,199917.0,199333.0,202917.0,206083.0,211167.0,212833.0,212667.0,211000.0,206667.0,206000.0,202000.0
91,"Jackson, MS",167200.0,166533.0,170050.0,173467.0,178667.0,184333.0,190167.0,192333.0,190000.0,187500.0,187167.0,183833.0
92,"Augusta, GA",165962.0,169717.0,165492.0,169675.0,169375.0,178183.0,181667.0,184000.0,181250.0,178750.0,178067.0,178783.0
93,"Harrisburg, PA",175650.0,174067.0,169717.0,171183.0,175017.0,178350.0,181450.0,183500.0,181850.0,181583.0,179950.0,181967.0
94,"Provo, UT",281817.0,289667.0,292167.0,295890.0,297023.0,303690.0,309967.0,309983.0,309250.0,306583.0,305933.0,308333.0
95,"Durham, NC",268500.0,267667.0,269833.0,276333.0,278000.0,279667.0,281333.0,283167.0,279833.0,278167.0,279775.0,288108.0
96,"Port St. Lucie, FL",216600.0,215600.0,218333.0,220000.0,223333.0,223333.0,224022.0,225655.0,227322.0,230573.0,228018.0,227148.0
97,"Vallejo, CA",418750.0,419417.0,425083.0,429333.0,434333.0,432667.0,436667.0,438500.0,435833.0,432333.0,432167.0,429167.0
98,"Killeen, TX",150100.0,149100.0,150150.0,155950.0,158250.0,161600.0,163137.0,164803.0,162787.0,160267.0,159952.0,159602.0
99,"Salem, OR",268333.0,270700.0,273850.0,280483.0,283017.0,284867.0,290633.0,295700.0,296033.0,289933.0,286300.0,286798.0
100,"Ocala, FL",146100.0,147117.0,147317.0,149233.0,149917.0,154750.0,159083.0,161250.0,162883.0,162800.0,163283.0,162283.0
101,"Fort Collins, CO",365992.0,369658.0,375492.0,377000.0,382333.0,382633.0,384567.0,382149.0,383116.0,382349.0,384962.0,383861.0
102,"Boulder, CO",500333.0,521633.0,524967.0,531300.0,548000.0,546333.0,536904.0,524294.0,526628.0,529723.0,535000.0,546936.0
103,"Clarksville, TN",163300.0,163300.0,163333.0,166983.0,169983.0,176950.0,180050.0,179383.0,176917.0,174333.0,173583.0,171583.0
104,"Greeley, CO",331667.0,331667.0,331467.0,335367.0,341700.0,341717.0,343268.0,342602.0,343570.0,344785.0,346918.0,349458.0
105,"Macon-Bibb County, GA",130287.0,119983.0,120817.0,127800.0,135600.0,139595.0,138078.0,138112.0,136300.0,134667.0,132667.0,134667.0
106,"Athens, GA",192800.0,196750.0,186442.0,199975.0,206375.0,213017.0,211967.0,207583.0,202583.0,196250.0,196220.0,195220.0
107,"Gainesville, GA",210350.0,212267.0,212150.0,229917.0,238167.0,234100.0,237400.0,233900.0,237967.0,230000.0,241000.0,239400.0
108,"Yuba City, CA",266000.0,270000.0,274667.0,279667.0,279000.0,286667.0,287500.0,289167.0,282500.0,280250.0,280083.0,286417.0
109,"Punta Gorda, FL",190167.0,191500.0,188750.0,195667.0,199000.0,206000.0,203233.0,203233.0,201533.0,203033.0,210700.0,212400.0
110,"Pueblo, CO",171467.0,171867.0,173567.0,179400.0,180833.0,188333.0,191667.0,192500.0,190000.0,185667.0,182300.0,178967.0
111,"Sherman, TX",163667.0,156067.0,164067.0,167900.0,180167.0,185167.0,190300.0,183047.0,184214.0,179914.0,187500.0,179000.0
112,"Dunn, NC",180300.0,176300.0,173467.0,174833.0,176817.0,178900.0,183817.0,183833.0,178167.0,170917.0,173583.0,179333.0
113,"Truckee, CA",432250.0,421667.0,428667.0,442000.0,448583.0,463250.0,465000.0,469917.0,463917.0,465667.0,458833.0,436500.0
114,"The Villages, FL",255862.0,259529.0,263461.0,259464.0,259964.0,263103.0,268070.0,265570.0,261833.0,263833.0,266333.0,273630.0
115,"Faribault, MN",208000.0,208667.0,206967.0,209300.0,208800.0,214667.0,218967.0,226235.0,228402.0,222586.0,217117.0,217451.0
116,"Albemarle, NC",141000.0,139167.0,143250.0,152250.0,149083.0,149000.0,144000.0,151083.0,152083.0,156750.0,153667.0,156667.0
117,"Kerrville, TX",235311.0,232145.0,232145.0,234167.0,245667.0,258667.0,260750.0,252083.0,235250.0,236667.0,245750.0,258750.0
118,"Shelbyville, TN",161400.0,165353.0,161120.0,161453.0,162267.0,163267.0,164100.0,164833.0,177167.0,177500.0,172833.0,159467.0
119,"Wilmington, OH",120133.0,109167.0,132500.0,130167.0,135133.0,128300.0,131800.0,131883.0,133217.0,129383.0,124167.0,122333.0

In [7]:
# Combine Multi City Metro's to match with the income data
# Build a copy to transform
zillow_transform_df = final_zillow_df.reset_index()

In [8]:
# Traverse the cities
for ind in zillow_transform_df.index: 
    
    #print(test_df['metro_area'][ind])
    input_str = zillow_transform_df['metro_area'][ind]
    
    # Remove the text from ''-' to ',' (keeps the primary city)
    input_str = re.sub(r'-.*,', '', input_str)
    
    # Where we have '-' leftover, those are between states, so keep the first state only
    input_str = input_str.split('-')[0]
    
    # Write it back to the dataframe
    zillow_transform_df.at[ind, 'metro_area'] = input_str

In [9]:
# Now, we traverse the cities again to clean up some newly created issues
# We now have no commas between cities and states
for ind in zillow_transform_df.index: 
    # Look for entries with no commas
    if zillow_transform_df['metro_area'][ind].find(',') == -1:
        #census_transform_df.at[ind, 'metro_area'] = census_transform_df['metro_area'][ind].replace(' ',', ')   
        
        # Find the last occurrance of a ' ' (this will be just before the state) and replace with a ','
        original_string = zillow_transform_df.at[ind, 'metro_area']
        last_space_index = original_string.rfind(' ')
        new_string = original_string[:last_space_index] + ", " + original_string[last_space_index+1:]
        
        # Write it back to the dataframe
        zillow_transform_df.at[ind, 'metro_area'] = new_string
       
    else:
        continue

In [10]:
zillow_transform_df.head(10)

,index,metro_area,Median Home Price 1/18,Median Home Price 2/18,Median Home Price 3/18,Median Home Price 4/18,Median Home Price 5/18,Median Home Price 6/18,Median Home Price 7/18,Median Home Price 8/18,Median Home Price 9/18,Median Home Price 10/18,Median Home Price 11/18,Median Home Price 12/18
0,0,"New York, NY",398500.0,395500.0,394667.0,395000.0,401666.0,410000.0,420000.0,425333.0,425333.0,417000.0,411000.0,404333.0
1,1,"Los Angeles, CA",612666.0,615666.0,620667.0,632333.0,639333.0,646667.0,651667.0,651952.0,646952.0,643618.0,641667.0,637667.0
2,2,"Chicago, IL",218833.0,218500.0,222167.0,230000.0,237333.0,243667.0,245333.0,243300.0,236633.0,229754.0,226121.0,222788.0
3,3,"Dallas, TX",251921.0,253588.0,255482.0,261661.0,268327.0,273333.0,276667.0,274000.0,267333.0,261333.0,258663.0,259997.0
4,4,"Philadelphia, PA",228300.0,225667.0,224000.0,229000.0,235000.0,241667.0,246667.0,251000.0,247833.0,242500.0,237467.0,235633.0
5,5,"Houston, TX",224089.0,223756.0,224323.0,231330.0,237497.0,241497.0,242500.0,240907.0,236907.0,232636.0,230729.0,234063.0
6,6,"Washington, DC",387982.0,388000.0,388000.0,398000.0,409333.0,415152.0,417318.0,414652.0,407500.0,399098.0,394431.0,399098.0
7,7,"Miami, FL",270000.0,269000.0,270667.0,274000.0,278333.0,283333.0,285582.0,285582.0,280582.0,280000.0,281667.0,283333.0
8,8,"Atlanta, GA",228300.0,229967.0,231100.0,237216.0,243648.0,247797.0,248681.0,245549.0,244133.0,243433.0,243670.0,242837.0
9,9,"Boston, MA",422300.0,420646.0,424646.0,436480.0,448133.0,462467.0,469967.0,473333.0,458333.0,444667.0,438000.0,435667.0

In [11]:
# Cleanup the DataFrame
del zillow_transform_df['index']
zillow_transform_df

,metro_area,Median Home Price 1/18,Median Home Price 2/18,Median Home Price 3/18,Median Home Price 4/18,Median Home Price 5/18,Median Home Price 6/18,Median Home Price 7/18,Median Home Price 8/18,Median Home Price 9/18,Median Home Price 10/18,Median Home Price 11/18,Median Home Price 12/18
0,"New York, NY",398500.0,395500.0,394667.0,395000.0,401666.0,410000.0,420000.0,425333.0,425333.0,417000.0,411000.0,404333.0
1,"Los Angeles, CA",612666.0,615666.0,620667.0,632333.0,639333.0,646667.0,651667.0,651952.0,646952.0,643618.0,641667.0,637667.0
2,"Chicago, IL",218833.0,218500.0,222167.0,230000.0,237333.0,243667.0,245333.0,243300.0,236633.0,229754.0,226121.0,222788.0
3,"Dallas, TX",251921.0,253588.0,255482.0,261661.0,268327.0,273333.0,276667.0,274000.0,267333.0,261333.0,258663.0,259997.0
4,"Philadelphia, PA",228300.0,225667.0,224000.0,229000.0,235000.0,241667.0,246667.0,251000.0,247833.0,242500.0,237467.0,235633.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,"Faribault, MN",208000.0,208667.0,206967.0,209300.0,208800.0,214667.0,218967.0,226235.0,228402.0,222586.0,217117.0,217451.0
116,"Albemarle, NC",141000.0,139167.0,143250.0,152250.0,149083.0,149000.0,144000.0,151083.0,152083.0,156750.0,153667.0,156667.0
117,"Kerrville, TX",235311.0,232145.0,232145.0,234167.0,245667.0,258667.0,260750.0,252083.0,235250.0,236667.0,245750.0,258750.0
118,"Shelbyville, TN",161400.0,165353.0,161120.0,161453.0,162267.0,163267.0,164100.0,164833.0,177167.0,177500.0,172833.0,159467.0
119,"Wilmington, OH",120133.0,109167.0,132500.0,130167.0,135133.0,128300.0,131800.0,131883.0,133217.0,129383.0,124167.0,122333.0

In [12]:
sales_average_df = zillow_transform_df.copy()
sales_average_df['2018 Sales Average'] = zillow_transform_df.sum(axis=1) / 12
pd.set_option('precision', 0)
sales_average_df.head()

,metro_area,Median Home Price 1/18,Median Home Price 2/18,Median Home Price 3/18,Median Home Price 4/18,Median Home Price 5/18,Median Home Price 6/18,Median Home Price 7/18,Median Home Price 8/18,Median Home Price 9/18,Median Home Price 10/18,Median Home Price 11/18,Median Home Price 12/18,2018 Sales Average
0,"New York, NY",398500,395500,394667,395000,401666,410000,420000,425333,425333,417000,411000,404333,408194
1,"Los Angeles, CA",612666,615666,620667,632333,639333,646667,651667,651952,646952,643618,641667,637667,636738
2,"Chicago, IL",218833,218500,222167,230000,237333,243667,245333,243300,236633,229754,226121,222788,231202
3,"Dallas, TX",251921,253588,255482,261661,268327,273333,276667,274000,267333,261333,258663,259997,263525
4,"Philadelphia, PA",228300,225667,224000,229000,235000,241667,246667,251000,247833,242500,237467,235633,237061